import csv
from collections import defaultdict

configfile: "../config/config.yaml"


def read_tsv(path):
    with open(path, newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


SAMPLE_ROWS = read_tsv(config["samples_tsv"])
UNIT_ROWS = read_tsv(config["units_tsv"])

SAMPLES = [row["sample"] for row in SAMPLE_ROWS]
UNITS = [row["unit"] for row in UNIT_ROWS]
REF = config["reference"]
GENOME = config["genome_name"]

UNIT_TO_SAMPLE = {row["unit"]: row["sample"] for row in UNIT_ROWS}
UNIT_TO_FQ1 = {row["unit"]: row["fq1"] for row in UNIT_ROWS}
UNIT_TO_FQ2 = {row["unit"]: row["fq2"] for row in UNIT_ROWS}

UNITS_BY_SAMPLE = defaultdict(list)
for row in UNIT_ROWS:
    UNITS_BY_SAMPLE[row["sample"]].append(row["unit"])


def fastq_r1(wildcards):
    return UNIT_TO_FQ1[wildcards.unit]


def fastq_r2(wildcards):
    return UNIT_TO_FQ2[wildcards.unit]


def unit_bams_for_sample(wildcards):
    return expand("results/alignment/units/{unit}.sorted.bam", unit=UNITS_BY_SAMPLE[wildcards.sample])


localrules: all

rule all:
    input:
        expand("results/qc/raw/{unit}_{read}_fastqc.html", unit=UNITS, read=["R1", "R2"]),
        expand("results/qc/trimmed/{unit}_{read}.trimmed_fastqc.html", unit=UNITS, read=["R1", "R2"]),
        "results/qc/multiqc/multiqc_report.html",
        expand("results/alignment/samples/{sample}.sorted.bam", sample=SAMPLES),
        expand("results/alignment/samples/{sample}.sorted.bam.bai", sample=SAMPLES),
        expand("results/alignment/stats/{sample}.samtools.stats.txt", sample=SAMPLES),
        "results/variants/cohort.raw.vcf.gz",
        "results/variants/cohort.filtered.vcf.gz",
        "results/variants/cohort.filtered.vcf.gz.tbi",
        "results/reports/variant_summary.tsv",
        "results/dag/dag.png"

include: "rules/qc.smk"
include: "rules/trimming.smk"
include: "rules/alignment.smk"
include: "rules/variant_calling.smk"
include: "rules/filtering.smk"
